.github/workflows/chromatic.yml, .gitignore, react/package-lock.json, react/package.json
This PR adds Chromatic to build our storybooks automatically on push
=> chore: add Chromatic to CI/CD pipeline

react/README.md, react/package-lock.json
This PR adds typescript generation to the readme
=> docs: add type generation section to readme

react/package-lock.json, react/package.json
=> chore: bump version to v0.0.3

.github/workflows/publish-react.yml, .npmrc, react/README.md, react/package-lock.json, react/package.json
This PR adds a workflow for publishing new versions to npm upon push to `alpha`, `beta` or `latest` branches. Also adds instructions for executing a release. 
`NPM_TOKEN` needs to be added as a secret.
=> build: automated publishing

react/src/Calendar/CalendarBase/utils.ts, react/src/theme/components/Button.ts
Build issues in projects using the latest beta, due to lodash import and vite build conflicting. Update imports to fix the issue.
Example error in console:
=> feat: lodash imports

react/package-lock.json, react/package.json, react/src/Dropdown/MultiSelect/MultiSelect.stories.tsx, react/src/Dropdown/MultiSelect/MultiSelectProvider.tsx, react/src/Dropdown/SelectContext.tsx, react/src/Dropdown/SingleSelect/SingleSelect.stories.tsx, react/src/Dropdown/SingleSelect/SingleSelectProvider.tsx, react/src/Dropdown/components/DropdownItem/DropdownItem.tsx, react/src/Dropdown/components/DropdownItem/DropdownItemTextHighlighter.tsx, react/src/Dropdown/components/MultiDropdownItem/MultiDropdownItem.tsx, react/src/Dropdown/components/MultiSelectCombobox/MultiSelectCombobox.tsx, react/src/Dropdown/components/MultiSelectCombobox/SelectedItems.tsx, react/src/Dropdown/components/MultiSelectItem/MultiSelectItem.tsx, react/src/Dropdown/components/MultiSelectMenu.tsx, react/src/Dropdown/components/SelectCombobox/ComboboxClearButton.tsx, react/src/Dropdown/components/SelectCombobox/SelectCombobox.tsx, react/src/Dropdown/components/SelectCombobox/ToggleChevron.tsx, react/src/Dropdown/components/SelectMenu.tsx, react/src/Dropdown/components/SelectPopover/SelectPopover.tsx, react/src/Dropdown/components/SelectPopover/SelectPopoverContext.tsx, react/src/Dropdown/utils/defaultFilter.ts, react/src/utils/storybook.tsx
Linked to a bunch of fixes in the upstream FormSG repository, see: 
- https://github.com/opengovsg/FormSG/pull/5192
- https://github.com/opengovsg/FormSG/pull/5137
- https://github.com/opengovsg/FormSG/pull/4922
- https://github.com/opengovsg/FormSG/pull/4778
=> fix: update dropdown component to be more reliable

react/package-lock.json, react/package.json, react/src/Dropdown/MultiSelect/MultiSelect.stories.tsx, react/src/Dropdown/MultiSelect/MultiSelectProvider.tsx, react/src/Dropdown/SelectContext.tsx, react/src/Dropdown/SingleSelect/SingleSelect.stories.tsx, react/src/Dropdown/SingleSelect/SingleSelectProvider.tsx, react/src/Dropdown/components/DropdownItem/DropdownItem.tsx, react/src/Dropdown/components/DropdownItem/DropdownItemTextHighlighter.tsx, react/src/Dropdown/components/MultiDropdownItem/MultiDropdownItem.tsx, react/src/Dropdown/components/MultiSelectCombobox/MultiSelectCombobox.tsx, react/src/Dropdown/components/MultiSelectCombobox/SelectedItems.tsx, react/src/Dropdown/components/MultiSelectItem/MultiSelectItem.tsx, react/src/Dropdown/components/MultiSelectMenu.tsx, react/src/Dropdown/components/SelectCombobox/ComboboxClearButton.tsx, react/src/Dropdown/components/SelectCombobox/SelectCombobox.tsx, react/src/Dropdown/components/SelectCombobox/ToggleChevron.tsx, react/src/Dropdown/components/SelectMenu.tsx, react/src/Dropdown/components/SelectPopover/SelectPopover.tsx, react/src/Dropdown/components/SelectPopover/SelectPopoverContext.tsx, react/src/Dropdown/utils/defaultFilter.ts, react/src/Toast/useToast.ts, react/src/utils/storybook.tsx, react/vite.config.ts
=> build: release v0.0.13 beta.5

react/src/Dropdown/MultiSelect/MultiSelectProvider.tsx, react/src/Dropdown/SelectContext.tsx, react/src/Dropdown/SingleSelect/SingleSelectProvider.tsx
Only on input blur should the input be cleared. Allows for easier usage of component.
**BEFORE**:
**AFTER**:
=> feat: update MultiSelect component to retain input on selection

react/package-lock.json, react/package.json, react/src/MultiSelect/components/MultiSelectItem/MultiSelectItem.tsx, react/src/Tag/Tag.tsx, react/src/TagInput/TagInput.stories.tsx, react/src/TagInput/TagInput.tsx, react/src/TagInput/TagInputInput.tsx, react/src/TagInput/TagInputProvider.tsx, react/src/TagInput/TagInputTag.tsx, react/src/TagInput/index.ts, react/src/theme/components/Tag.ts, react/src/theme/components/TagInput.ts, react/src/theme/components/index.ts
Missed migrating this from FormSG. It's here now!
=> feat: add TagInput component

react/package-lock.json, react/package.json, react/src/DatePicker/components/DatePickerInput.tsx, react/src/DateRangePicker/components/DateRangePickerInput.tsx, react/src/FormControl/FormHelperText/FormHelperText.tsx, react/src/Input/Input.tsx, react/src/SingleSelect/components/SelectCombobox/SelectCombobox.tsx, react/src/theme/components/SingleSelect.ts
Upgrades to the latest version of `@chakra-ui/react` which contains a [helpful fix](https://github.com/chakra-ui/chakra-ui/pull/7315) for the `Menu` component.
=> feat: upgrade chakra-ui to v2.5.0 to fix Menu

react/src/theme/foundations/semanticTokens.ts, react/src/theme/theme.ts
This PR adds default semantic tokens to the default theme
=> feat(theme): add default body text, bg, borderColor semantic tokens

react/src/Tag/Tag.stories.tsx, react/src/theme/components/Tag.ts
This PR implements `xs` size themes for the `Tag` component.
Stories have also been updated
=> feat(Tag): add xs size and styles

react/.storybook/main.ts, react/.storybook/preview.tsx, react/package-lock.json, react/package.json, react/src/Menu/Menu.stories.tsx
Instead of homegrown theming addon (which is the same thing la, but this one officially supported)
=> feat: use @storybook/addon-styling addon for theming in storybook

react/src/theme/components/MultiSelect.ts
Padding was off, this PR fixes it.
=> fix(MultiSelect): correct chevron height on sm size

react/package-lock.json, react/package.json
This PR updates the above packages to latest
=> fix: update chakra-ui/react, chakra-ui/cli and typescript to latest

react/README.md
=> chore: add build issue remediation in Readme

react/src/Tile/Tile.tsx
Allow style overrides on `Tile`
=> feat(tile): allow style overrides

react/.storybook/introduction/Welcome/Welcome.tsx
Camp is now in use in multiple OGP products, so change one word to reflect this. Take the trouble also to tidy up the para
=> fix(welcome): FormSG -> OGP, rearrange text

react/.storybook/introduction/Principles/Principles.tsx
- `User centred` -> `User-Centred`
- Move the word `aesthetics` into the title
=> fix(principles): correct wording, punc

react/README.md
=> chore(react-readme): point to updated Storybook URL

react/src/Banner/Banner.stories.tsx, react/src/Banner/Banner.tsx, react/src/theme/components/Banner.ts
=> fix: set standard banner padding regardless of viewport, add sm size

react/package-lock.json, react/package.json
if not, ogpds will break on cjs systems
=> fix: downgrade to nanoid@3 to retain cjs compatbility

react/src/RestrictedGovtMasthead/RestrictedGovtMasthead.tsx
=> fix: masthead alignment and icon sizing

react/src/RestrictedFooter/RestrictedFooter.stories.tsx, react/src/RestrictedFooter/RestrictedFullFooter.tsx
fix(Footer): invalid DOM nesting when React Element is used as appName
feat(Footer): update footer story for custom app name element
=> fix(Footer): invalid DOM nesting when React Element is used as appName

react/src/Badge/Badge.stories.tsx, react/src/Badge/Badge.tsx, react/src/theme/components/Badge.ts
Closes #614 and fixes some other colour issues with badges.
=> fix: badge colors

react/package-lock.json, react/package.json, react/src/Attachment/Attachment.stories.tsx
incompatible with GSIB, reverting whilst we investigate
=> feat: revert react-dropzone to v11

react/src/DatePicker/DatePicker.stories.tsx, react/src/DatePicker/DatePickerContext.tsx
Similar to #680, but for `DatePicker` component
=> fix(DatePicker): render new value when `value` prop changes

.github/workflows/publish-react.yml
Don't need keep switching to NPM and back
=> chore: dual publish to github

react/.storybook/introduction/Principles/Principles.tsx, react/package-lock.json, react/package.json, react/src/Spinner/SpinnerIcon.tsx, react/src/Switch/Switch.tsx
breaks some esm imports in the latest chakra version it seems
=> feat: use @chakra-ui/react imports over specialised imports

package-lock.json, packages/camp/package.json, packages/camp/src/Banner/Banner.tsx, packages/camp/src/FormControl/FormHelperText/FormHelperText.stories.tsx, packages/camp/src/Radio/Radio.tsx, packages/camp/src/RestrictedGovtMasthead/RestrictedGovtMastheadItem.tsx, packages/camp/src/SingleSelect/types.ts, packages/camp/src/SingleSelect/utils/itemUtils.ts, packages/camp/src/Tile/Tile.tsx, packages/camp/src/Tooltip/Tooltip.tsx
Bumps @chakra-ui for a translation related bug fix: https://github.com/chakra-ui/chakra-ui/issues/8238
Fix was introduced in [`ac31c4b`](https://github.com/chakra-ui/chakra-ui/commit/ac31c4bbaa737cc1f947e5c2c6c2f2f228ad500b) and released in v2.10.0.
=> chore(deps): bump @chakra-ui packages

.github/workflows/chromatic.yml, .github/workflows/publish-camp.yml
closes https://github.com/opengovsg/camp-design-system/issues/888
=> ci: pin dorny/paths-filter github action to sha
