react/package-lock.json
react/package.json
react/rollup.config.js

Fixes bug where node imports were erroneously expected when imported, due to `react-markdown` using node-only `process` package. 
Instead of shimming, move `react-markdown` to peer dependency so the correct packages are pulled from npm.

build: release v0.0.4

---

react/README.md
react/package-lock.json
react/package.json
react/rollup.config.js
react/src/Attachment/utils/getInvalidAttachments.ts
react/src/Tile/Tile.stories.tsx
react/src/hooks/useMdComponents.tsx
react/src/icons/BxCheckAnimated.tsx

Attempt to make this package fully compatible with cjs, drop support for esm.
create-react-app was installing this package correctly, but nextjs was not. This was due to react-markdown being esm-only.
Add README steps to fix issues with nextjs, which is to specifically install react-markdown@6 until nextjs is configured to use esm

build: release v0.0.5

---

react/README.md

`libphonenumber-js` is a peerDependency which is required to use some components in this design system. However, when the library is not installed, an unhelpful error message is shown, leading to possible confusion.
Adds the error message to the README so developers can easily find out the solution to the problem. (Install libphonnumber-js)

docs: adds libphonenumberjs imissing error and solution to README

---

netlify.toml

Netlify preview builds run on every PR even when mdx files are unchanged. 
Chromatic review already takes care of component/story changes so netlify preview builds are not needed when mdx files aren't changed
Add a `netlify.toml` file to configure netlify builds.
The file specifies that if no (nested or not) mdx files in `react/src` are changed, then don't build a netlify preview
You can see that this PR has no netlify preview. (It shows cancelled)

feat: disables netlify build when mdx files are not changed

---

react/package-lock.json
react/package.json

This release upgrades React dependency to React 18. Since this package is still below v1.0.0, semver is not followed. 
This package may not work properly with React 17 codebases. 
Please stay on `v0.0.6` or `v0.0.7-beta.0` if using React 17 or below.

build!: bump version to 0.0.8

---

react/src/IconButton/IconButton.stories.tsx

Fix broken story for IconButton by ensuring that args provided are serializable;
move hardcoded icon property from args to template to ensure this

fix(icon-button): do not provide objects as args

---

react/src/DatePicker/index.ts

Closes #37
Re-export the components from `DateInput`, `DatePicker`, `DateRangeInput`, and `DateRangePicker` in `DatePicker/index.ts`.

fix: export missing date-related elements

---

react/src/theme/components/Form.ts
react/src/theme/components/FormError.ts

1. Text for form field success and error messages are not aligned with icon:
2. Height for form field info and success messages are not of the same height (64 vs 61), which causes height of form to change based on validation.
This is fixed in FormSG, but not in the design system.
https://github.com/opengovsg/FormSG/blob/form-v2/develop/frontend/src/theme/components/Form.ts
https://github.com/opengovsg/FormSG/blob/form-v2/develop/frontend/src/theme/components/FormError.ts

fix: align form info and error text with icon

---

react/vite.config.ts

Encountering `TypeError: $2.zonedTimeToUtc is not a function` in downstream project using current version. This change configures `date-fns-tz` imports correctly so it finds the function.

fix: update vite config to fix downstream build

---

react/src/Toast/useToast.ts

Update `useToast` component to accept a duration param.

feat: don't hardcode toast duration

---

react/src/RestrictedFooter/RestrictedFooter.tsx
react/src/RestrictedFooter/common/types.ts
react/src/RestrictedFooter/index.ts

Types for the `RestrictedFooter` component were not exported. This PR exports them.

feat: export RestrictedFooter types and constants

---

react/package.json

Fixes bug with storybook theme not rendering.
Not sure if `sideEffects` is needed, will need more testing for tree-shakeability changes, but resulting packed size did not change (so suspect no code differences) See https://github.com/storybookjs/storybook/issues/20704

build: remove sideEffects prop from package.json

---

react/package-lock.json
react/package.json

#200 installs `nanoid`, which dropped CJS support in v4. This results in failing builds downstream:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/cal-sg/cal-sg/frontend/node_modules/@opengovsg/design-system-react/node_modules/nanoid/non-secure/index.js from /home/runner/work/cal-sg/cal-sg/frontend/node_modules/@opengovsg/design-system-react/build/main/Calendar/CalendarBase/CalendarContext.js not supported.
Instead change the require of index.js in /home/runner/work/cal-sg/cal-sg/frontend/node_modules/@opengovsg/design-system-react/build/main/Calendar/CalendarBase/CalendarContext.js to a dynamic import() which is available in all CommonJS modules.
```
Solution is to downgrade to v3, which will be [supported](https://github.com/ai/nanoid/blob/main/CHANGELOG.md#40) …

feat: downgrade nanoid to latest CJS-supported version

---

react/src/Radio/Radio.stories.tsx
react/src/Radio/Radio.tsx

Currently, all `Radio` fields can be deselected. This works for cases where radio fields are optional (e.g. optional fields in FormSG), but not for cases where one option must be selected at all times (e.g. in most settings pages).
Add an `allowDeselect` prop which defaults to `true` for backwards compatibility. Set to `false` for radio buttons which should not be deselected.

feat(Radio): add allowDeselect option

---

react/src/Banner/Banner.tsx
react/src/FormControl/FormLabel/FormLabel.tsx
react/src/Infobox/Infobox.tsx
react/src/Toast/Toast.tsx
react/src/Toast/useToast.ts
react/src/hooks/useMdComponents.tsx
react/src/types/WithSsr.ts

When `useMdComponent` is used in an SSR environment, a hydration mismatch will occur due to the use of `window.location` when checking whether links are external.
This commit adds the `ssr` and `link.isExternalFn` prop for use in SSR environment to prevent a hydration mismatch. However, external icons will no longer render and there is a need to use the `link.isExternalFn` fn to calculate external-ness in an ssr environment.

feat: add ssr, link.isExternalFn props to useMdComponent hook

---

react/src/Calendar/CalendarBase/CalendarHeader.tsx
react/src/Calendar/CalendarBase/DayOfMonth.tsx
react/src/DatePicker/components/DatePickerContentBase.tsx
react/src/theme/components/Attachment.ts
react/src/theme/components/Badge.ts
react/src/theme/components/Button.ts
react/src/theme/components/Checkbox.ts
react/src/theme/components/Input.ts
react/src/theme/components/Link.ts
react/src/theme/components/Modal.ts
react/src/theme/components/MultiSelect.ts
react/src/theme/components/Pagination.ts
react/src/theme/components/Tag.ts
react/src/theme/components/Tile.ts
react/src/theme/components/Toast.ts
react/src/theme/components/Tooltip.ts

Since we have the radius token (default from [Chakra theme](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/theme/src/foundations/radius.ts)), might as well use it for consistency

feat: replace usage of borderRadius with token

---

react/src/Searchbar/Searchbar.tsx

Some projects want to implement dynamic searches using design system (i.e. searching on change rather than on keydown Enter), but right now it's a bit clunky. The current workaround is to do this:
```javascript
const Component = () => {
const handleSearch = (searchterm: string) => { return stuff }
// Other stuff here
return (
<Searchbar 
onChange = {(e) => handleSearch(e.currentTarget.value)} 
onSearch = {handleSearch} // Actually not required
/>
)
}
```
Make `onSearch` optional, and add an optional `onChange` prop. This means that users may choose one or the other, and will not be required to implement both.
Since there's a change to the type of `onChange`, this might be breaking for some people.
Feel free to close if unwanted though

feat: add onChange prop to searchbar to enable dynamic search

---

react/package-lock.json
react/package.json
react/src/MultiSelect/MultiSelectProvider.tsx
react/src/MultiSelect/components/MultiDropdownItem/MultiDropdownItem.tsx
react/src/MultiSelect/components/MultiSelectCombobox/MultiSelectCombobox.tsx
react/src/MultiSelect/components/MultiSelectCombobox/SelectedItems.tsx
react/src/SingleSelect/SelectContext.tsx
react/src/SingleSelect/SingleSelectProvider.tsx
react/src/SingleSelect/components/SelectCombobox/ComboboxClearButton.tsx
react/src/SingleSelect/components/SelectCombobox/SelectCombobox.tsx
react/src/SingleSelect/components/SelectCombobox/ToggleChevron.tsx

Supersedes #215
The single select component is not fully accessible according to the [W3C WAI standard for comboboxes](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/). Some bugs in the old implementation included: 
- Input aria defined outside of the input element itself, making it hard to find where the currently-selected option is said.
- Overlapping stack and input within the combobox itself, which confuses screen readers by adding an additional `->` step
- Navigating to the combobox instantly toggling the menu, thus causing focus to jump around different components at unexpected times
- Clear selection not announcing input clearing correctly.
This PR fixes these issues. 
At the same time, I also took the chance to upgrade downshift, which means …

fix: upgrade downshift from 6.1.12 to 7.2.0, a11y fixes for single select and multiselect

---

react/src/MultiSelect/components/MultiSelectCombobox/MultiSelectCombobox.tsx

This PR fixes a bug where the `isSearchable` prop does nothing on `MultiSelect` components.

fix(MultiSelect): set input to readonly if isSearchable is false

---

react/src/theme/components/Link.ts

when removing focus on links, there would be a wonky focus ring expansion animation due to outline offset changing from 0 to 2px. Setting the offset on the root style stops that from happening

fix: add outline offset to default link styles

---

react/src/theme/components/Avatar.ts
react/src/theme/components/AvatarMenu.ts
react/src/theme/components/Tag.ts

token names were changed but components theme declaration was missed

fix: use `-subtle` colors instead of non-existant `-light` prefix

---

react/src/Sidebar/NestedSidebarItem.tsx
react/src/Sidebar/Sidebar.stories.tsx
react/src/Sidebar/Sidebar.tsx
react/src/Sidebar/SidebarCollapseButton.tsx
react/src/Sidebar/SidebarContainer.tsx
react/src/Sidebar/SidebarContext.tsx
react/src/Sidebar/SidebarItem.tsx
react/src/Sidebar/SidebarSection.tsx
react/src/icons/BxArrowToLeft.tsx
react/src/icons/BxArrowToRight.tsx
react/src/icons/index.ts
react/src/theme/components/Sidebar.ts

> Builds on #233 
TODO (will be done in future PRs):

feat: allow collapsing of sidebar

---

react/package-lock.json
react/package.json
react/src/DatePicker/DatePickerContext.tsx
react/src/DateRangePicker/DateRangePickerContext.tsx

Date picker was using the midnight of the date picked and taking into account the timezone where the user is filling in the form. However, it does not make sense to do so as users will be picking particular dates rather than timings, and the understanding of the different timezones should be established as part of the question.
Same fix added to [FormSG](https://github.com/opengovsg/FormSG) on https://github.com/opengovsg/FormSG/pull/6025
Remove the portions of the code to account for timezone differences. This allows the text field of the calendar field to reflect the date selected on the date picker.
**Breaking Changes** 
**Bug Fixes**:
- Remove timezone conversions previously included in datepicker

fix: remove timezone from datepicker

---

react/src/Sidebar/SidebarHeader.tsx
react/src/Sidebar/types.ts

Allow chakra props (e.g. `px`, `position`, etc) to be passed into Sidebar's underlying components.
Currently already does that since props are spread into the components, but the typings do not show it. This PR adds the correct typings into the component.

feat: allow ChakraProps to be used in Sidebar components

---

react/src/MultiSelect/MultiSelectProvider.tsx
react/src/SingleSelect/SingleSelectProvider.tsx

Previously, the size was set to default to 'md' in the SelectProviders, but this meant setting the size as a default prop in the theme declaration would always be overridden by the default size assignment in the component itself.
This PR fixes that by setting the respective `size` priority to be:
size prop > theme prop > 'md' assignment if does not exist in theme

fix: respect size defaultProps in MultiSelect, SingleSelect component

---

react/src/Banner/Banner.tsx

Closes #398 
In the third line, the code was previously as follows. It does not return the custom close button, so the function continues and returns the default close button, regardless of whether the `closeButton` prop was passed in or not.
```js
const closeButtonRendered = useMemo(() => {
if (!isDismissable) return null
if (closeButton !== undefined) closeButton
return (
<CloseButton children={<BxX />} onClick={onToggle} sx={styles.close} />
)
}, [closeButton, isDismissable, onToggle, styles.close])
```
The fix is to change the third line to
```if (closeButton !== undefined) return closeButton```
Example (local edit in `Banner.stories.tsx`)

fix: custom close button for banner

---

react/src/Calendar/Calendar.stories.tsx
react/src/Calendar/Calendar.tsx
react/src/Calendar/CalendarBase/CalendarContext.tsx
react/src/Calendar/CalendarBase/CalendarHeader.tsx
react/src/Calendar/CalendarBase/CalendarPanel.tsx
react/src/Calendar/CalendarBase/types.ts
react/src/Calendar/RangeCalendar.stories.tsx
react/src/Calendar/RangeCalendar.tsx
react/src/DatePicker/DatePicker.stories.tsx
react/src/DatePicker/DatePickerContext.tsx
react/src/DatePicker/components/DatePickerCalendar.tsx
react/src/DatePicker/types.ts
react/src/DatePicker/utils/index.ts
react/src/DatePicker/utils/pickCalendarProps.ts
react/src/DateRangePicker/DateRangePicker.stories.tsx
react/src/DateRangePicker/DateRangePickerContext.tsx
react/src/DateRangePicker/components/DateRangePickerCalendar.tsx
react/src/theme/components/Calendar.ts

Closes #411
This PR adds a new prop `isCalendarFixedHeight` to the `Calendar` and `DatePicker`/`DateRangePicker` components so the calendar will not change in height on when navigating between months, resulting in poorer UX. 
Also add `showTodayButton` prop to hide or show the button.
```tsx
/**
* Whether to set the calendar to always be a fixed height.
* This is useful for ensuring that the calendar does not jump around when the user switches between months
* if the months have different numbers of weeks and the calendar is positioned from the bottom.
* @default false
*/
isCalendarFixedHeight?: boolean
/**
* Whether to show or hide the button to focus on Today.
* @default true
*/
showTodayButton?: boolean
```
This PR also improves the UX of mobile drawer for daterangepicker, reducing the …

feat(calender/datepicker):  allow fixed height and mobile UX improvements

---

react/.storybook/preview.tsx
react/src/Checkbox/Checkbox.stories.tsx
react/src/Checkbox/Checkbox.tsx
react/src/theme/components/Checkbox.ts
react/src/theme/utils/contrast.ts

> This PR is built on @austinwoon's initial work in https://github.com/opengovsg/design-system/pull/396
This PR adds a darkmode variant to Checkbox. To use it even in light mode, just wrap the component (or any parent) with ChakraUI's `DarkMode` component.
e.g.
```tsx
import { DarkMode } from '@chakra-ui/react'
import { Checkbox } from '@opengovsg/design-system-react'
const DarkmodeCheckbox = () => <DarkMode><Checkbox>Darkmode</Checkbox></Darkmode>
```
Also add `inverse` colorScheme to Checkbox, but the color will default to `main` colours

feat: add darkmode to checkbox, inverse colorScheme

---

.github/workflows/chromatic.yml

ignore any changes in .storybook/colorThemes directory, turbosnap always gets disabled because no files can be traced to those directories, yet always gets scanned for some reason

feat(ci): finetune when turbosnap for chromatic runs

---

react/src/Checkbox/Checkbox.stories.tsx

Checkbox stories were showing unnecessary or undeveloped colorSchemes in dark mode. This PR updates Checkbox's darkmode story to show only the supported darkmode colorSchemes

feat(checkbox): display relevant checkbox colorschemes in darkmode

---

react/src/MultiSelect/MultiSelect.stories.tsx
react/src/MultiSelect/MultiSelectProvider.tsx
react/src/MultiSelect/components/MultiSelectMenu.tsx
react/src/SingleSelect/SingleSelect.stories.tsx
react/src/SingleSelect/SingleSelectProvider.tsx
react/src/SingleSelect/components/SelectMenu.tsx
react/src/SingleSelect/constants.ts
react/src/theme/components/SingleSelect.ts

MultiSelect and SingleSelect components rely on fixed heights for items. 
```typescript
// SingleSelect/constants.ts
export const VIRTUAL_LIST_ITEM_HEIGHT = {
xs: 40,
sm: 40,
md: 48,
}
```
However, when descriptions are added, item height exceed fixed constant and overflows the computed virtualListHeight.
```typescript
export const VIRTUAL_LIST_MAX_HEIGHT = {
xs: 4 * VIRTUAL_LIST_ITEM_HEIGHT.xs,
sm: 4 * VIRTUAL_LIST_ITEM_HEIGHT.sm,
md: 4 * VIRTUAL_LIST_ITEM_HEIGHT.md,
}
```
E.g. list becomes scrollable with only one item
Allow overriding of list item height.

feat: allow overriding of item height in virtual list

---

react/src/Tooltip/Tooltip.tsx

Tooltip label typing (`string`) is more restrictive from Chakra's. This makes it harder to control the label that is displayed when the tool tip is opened.
**Improvements**:
- Update label typing to be the same as that on Chakra

fix: label typing tooltip to match chakra

---

react/src/Searchbar/Searchbar.stories.tsx
react/src/Searchbar/Searchbar.tsx

Support for controlled searchbars was introduced in #218. However, the clear button does not trigger the `onChange` function and only supports uncontrolled inputs.
Closes #446 
Check if the searchbar is a controlled input by checking for the presence of `onChange`. If it is a controlled input, call `onChange` with the appropriate value.

fix(searchbar): clear controlled searchbar

---

react/src/Infobox/Infobox.stories.tsx
react/src/Infobox/Infobox.tsx
react/src/theme/components/Infobox.ts

Current infobox only has 'info', 'warning', 'error' variants but no success.
Add 'success' variant.

feat: add success variant for infobox component

---

react/src/Badge/Badge.tsx
react/src/Banner/Banner.tsx
react/src/Button/Button.tsx
react/src/FormControl/FormHelperText/FormHelperText.tsx
react/src/IconButton/IconButton.tsx
react/src/Infobox/Infobox.tsx
react/src/Menu/Menu.tsx
react/src/RestrictedFooter/common/types.ts
react/src/Tile/Tile.tsx
react/src/theme/components/Badge.ts
react/src/theme/components/Banner.ts
react/src/theme/components/Button.ts
react/src/theme/components/Infobox.ts
react/src/theme/components/Menu.ts

When users of OGPDS adds variants to certain components, the component's `variant` prop does not update to the new available variants, affecting intellisense and forcing users to ignore the invalid typescript type error. This PR removes all explicit variant type declarations and use `ThemingProps<Component>['variant']` as the type instead, so the types updates properly when `chakra-cli` is run.

feat: remove explicit variant type declarations in component props

---

react/src/Button/Button.stories.tsx
react/src/DatePicker/components/DatePickerContent.tsx
react/src/DatePicker/components/DatePickerContentBase.tsx
react/src/DateRangePicker/components/DateRangePickerContent.tsx
react/src/MultiSelect/components/MultiDropdownItem/ItemCheckboxIcon.tsx
react/src/MultiSelect/components/MultiDropdownItem/MultiDropdownItem.tsx
react/src/Toolbar/Toolbar.stories.tsx
react/src/theme/components/Attachment.ts
react/src/theme/components/Button.ts
react/src/theme/components/Checkbox.ts
react/src/theme/components/DatePicker.ts
react/src/theme/components/Menu.ts
react/src/theme/components/Modal.ts
react/src/theme/components/MultiSelect.ts
react/src/theme/components/PhoneNumberInput.ts
react/src/theme/components/SingleSelect.ts
react/src/theme/components/Toolbar.ts

"white" was used for the color token of many components in the design system. When a theme is by default dark mode, like PinPoint, many components break. This PR changes the declaration of "white" to `utility.ui` design token wherever it made sense, to unbreak themes like PinPoint.
This PR also allows for theme overrides for:
* DatePicker and DateRangePicker's calendar container via `styles.container` prop, and
* MultiSelect's menu list's check container via `styles.checkContainer` prop.
so custom themes can override styling for the relevant date picker and multiselect containers.
Previously, the background for the datepicker calendar container was hardcoded. it now takes the theme's `container` styles.
Chromatic should have no differences
(pinpoint theme)

feat(theme): use `utility.ui` token instead of hardcoding "white"

---

react/package-lock.json
react/src/Attachment/Attachment.stories.tsx

Attachment stories had regression due to adding default args to `parameters` object instead of `args`. Also highlights the importance of running chromatic on package updates...

feat(attachment): correctly set default args in story

---

react/README.md

The path to the default theme file was wrong.
Correct the path to `node_modules/@opengovsg/design-system-react/build/main/theme/theme.js` on `react/README.md`.

docs: correct path to theme.js

---

react/src/Sidebar/SidebarList.tsx

Closes #517
- Refactor `SectionWrapper` to not return chakra factory, but be a conditional wrapper that forwards props over to the child chakra div or button. This is so that the `type=button` prop can be passed to the button element.

fix: type button and refactor SectionWrapper

---

react/src/DatePicker/DatePickerContext.tsx
react/src/DatePicker/components/DatePickerInput.tsx
react/src/DatePicker/types.ts
react/src/DateRangePicker/DateRangePickerContext.tsx
react/src/DateRangePicker/components/DateRangePickerInput.tsx

that was causing some form validation to prevent submission, since the underlying value does not fit the pattern.
to allow users to still have the preference (since it does improve the UX greatly), add a new `experimental_forceIosNumberKeyboard` prop that does the same thing instead. 
docs:
```ts
/**
* Whether to force the number keyboard on iOS.
*
* This will set the inputmode to `numeric` and pattern to `[0-9]*` on the input, which
* will force the number keyboard to show on iOS for a better user experience.
*
* ⚠️ This will break native form input validation if set, since the value of the input
* will always be `"DD/MM/YYYY"`, which does not conform to the input.
* To prevent native form validation, set `noValidate` on the parent `form` component.
*/
```

fix: remove `pattern` prop on datepickers, add `experimental_forceIosNumberKeyboard` prop to trigger it instead

---

react/src/Tooltip/Tooltip.tsx
react/src/Tooltip/TouchableTooltip.stories.tsx

The `delay` prop will not work on OGPDS's `Tooltip` component as the open state is controlled. This is not ideal and a subtle misbehaviour. To fix that, this PR removes the `delay` prop from the component and directs users to use ChakraUI's `Tooltip` component if the prop is needed. 
To better communicate this change, the original OGPDS `Tooltip` component has been renamed `TouchableTooltip`. The original `Tooltip` component has also been aliased to prevent breaking changes, but is marked as deprecated. 
Closes https://github.com/opengovsg/design-system/issues/546

feat: rename Tooltip to TouchableTooltip

---

react/src/FormControl/FormLabel/FormLabel.tsx

feat(FormLabel): allow ReactNode instead of string

---

react/src/Calendar/Calendar.stories.tsx
react/src/Calendar/CalendarBase/CalendarContext.tsx
react/src/Calendar/CalendarBase/types.ts
react/src/Calendar/RangeCalendar.stories.tsx
react/src/DatePicker/DatePicker.stories.tsx
react/src/DatePicker/DatePickerContext.tsx
react/src/DatePicker/utils/pickCalendarProps.ts
react/src/DateRangePicker/DateRangePicker.stories.tsx
react/src/DateRangePicker/DateRangePickerContext.tsx

This PR adds a new prop on Calendar and DatePicker components to allow selection of "today's date" when the "Today" button is clicked in the components.
Also fixed some erroneous passing of props to the input component via `useFormControlProps`

feat(calendar/datepicker): add `shouldSetDateOnTodayButtonClick` prop to select date on today click

---

react/src/DatePicker/DatePicker.stories.tsx
react/src/DatePicker/components/DatePickerWrapper.tsx

The custom input element for `DatePicker` does not work in mobile view.

fix: date picker mobile custom input

---

react/src/DatePicker/components/CalendarButton.tsx
react/src/DatePicker/components/DatePickerOverlay.tsx
react/src/DatePicker/components/DatePickerWrapper.tsx
react/src/DateRangePicker/components/CalendarButton.tsx
react/src/DateRangePicker/components/DateRangePickerOverlay.tsx
react/src/DateRangePicker/components/DateRangePickerWrapper.tsx
react/src/theme/components/DatePicker.ts

Ancient bug that has been in design system since its inception!
previously, when clicking on the calendar button, the calendar popover will open. If the button is clicked again, the open popover will be  blurred, but the button will set the open state to "open" again (since the button triggers the open state). However, since the popover was in its closing animation, the popover will not open again. This results in a state desynchronisation between the state and the render, and the date picker cannot be opened again.
The easiest fix is to add a full screen overlay behind the popover when it is open, so any click outside will blur the calendar before allowing any other elements to be clicked.

fix: allow correct toggling of datepicker/daterangepicker with calendar button

---

react/src/theme/components/Modal.ts

mobile phones have bottom nav bars nowadays. If `100vh` was used, buttons that are sticky on the bottom will be hidden below the nav bar. Use `100dvh` instead (which is allowed by ChakraUI's shorthand `$100vh`, which only uses dvh if the media query is supported)

fix: use dvh ($100vh) in full screen modals

---

react/src/Toolbar/utils/useToolbarButtonProps.ts
react/src/theme/components/AvatarMenu.ts
react/src/theme/components/Banner.ts
react/src/theme/components/Breadcrumb.ts
react/src/theme/components/Button.ts
react/src/theme/components/Calendar.ts
react/src/theme/components/Checkbox.ts
react/src/theme/components/CloseButton.ts
react/src/theme/components/Link.ts
react/src/theme/components/Radio.ts
react/src/theme/components/Sidebar.ts
react/src/theme/components/Switch.ts
react/src/theme/components/Tabs.ts
react/src/theme/components/Tag.ts

Currently, to override the focus styles in various components such as a button, users would have to:
1. create a new layer style
2. for every component, override specific focus props to use the imported layer style
This should not happen often, since the current focusRing layer styles depends on the color token `utility.focus.default`, and the color can be changed without touching the layer style declaration simply by changing the `utility.focus.default` color alias to their intended color. However, if users want to change the _style_ of the layer style, there is currently no easy way to do so, until this PR.
This was very tedious and not very extensible.
This PR allows user to only need to do Step 1, and all components that rely on that particular focus layer style should automatically …

feat: allow users to change focusRing layerStyle in component theme

---

react/src/Tooltip/Tooltip.tsx
react/src/Tooltip/TouchableTooltip.stories.tsx

Allow touchable tooltip to have no arrows, requested by @prasanthkumaar.

feat: allow arrow override touchable tooltip

---

react/src/theme/components/Input.ts
react/src/theme/components/MultiSelect.ts

This PR fixes a regression with the `Input` and `MultiSelect` component if users use ChakraUI v2.8.2, where the height of the Input exported by design system is overridden by Chakra's default theme.
This happens because OGPDS's `Input` uses `h` prop alias for height, whilst ChakraUI v2.8.2 switched to using the `height` non-alias prop.
This PR is a fix to allow for backwards compatibility by using both redundant props.

fix(inputs): regression with ChakraUI v2.8.2 due to new `height` usage

---

react/src/DatePicker/DatePickerContext.tsx

A bug was introduced in #687 which prevented the input from changing when in a controlled state. This PR fixes that.

fix: allow input change when DatePicker is a controlled component

---

react/src/TagInput/TagInput.tsx

Supports `,`s in TagInput tags by allowing users to specify a `splitTagSeparator` which otherwise defaults to `,`. Any tag splitting is ignored if set as `null`.
For example: `splitTagSeparator = null & keyDownKeys = ['Enter']`:

feat: allow users to specify tag input string separator

---

react/src/DatePicker/DatePicker.stories.tsx
react/src/DatePicker/DatePickerContext.tsx
react/src/DatePicker/components/DatePickerWrapper.tsx
react/src/DatePicker/types.ts

This allows users to use datepicker hooks in their custom input component.
Currently, if `useDatepicker` hook is used in the custom input element,
react will throw (since the custom component is instantiated without a datepicker parent)

fix!(DatePicker): add `renderInputElement` prop

---

react/src/DatePicker/DatePicker.stories.tsx
react/src/DatePicker/DatePickerContext.tsx
react/src/DatePicker/components/DatePickerInput.tsx
react/src/DatePicker/types.ts
react/src/DateRangePicker/DateRangePicker.stories.tsx
react/src/DateRangePicker/DateRangePickerContext.tsx
react/src/Input/Input.tsx
react/src/MultiSelect/MultiSelect.stories.tsx
react/src/MultiSelect/MultiSelectProvider.tsx
react/src/SingleSelect/SingleSelect.stories.tsx
react/src/SingleSelect/SingleSelectProvider.tsx
react/src/theme/components/DatePicker.ts
react/src/theme/components/DateRangePicker.ts

This PR fixes the regression where `isPrefilled` state started to do nothing on the `Input` component due to downstream ChakraUI changes on their Input component.
This PR also adds the `isPrefilled` prop to the following components:
- `SingleSelect`
- `MultiSelect`
- `DatePicker`
- `DateRangePicker`
The prefilled styling follows the styling of the `Input` component.
See storybook for details.

feat: fix Input prefill style regression, add `isPrefilled` prop to Datepicker and Select

---

react/.storybook/foundations/Colours/ColourTable.tsx
react/.storybook/foundations/Typography/Typography.tsx
react/.storybook/introduction/Principles/Principles.stories.tsx
react/package.json
react/src/Attachment/Attachment.tsx
react/src/AvatarMenu/AvatarMenu.tsx
react/src/Calendar/CalendarBase/CalendarContext.tsx
react/src/Calendar/CalendarBase/DayOfMonth.tsx
react/src/DatePicker/utils/pickCalendarProps.ts
react/src/FormControl/FormHelperText/FormHelperText.tsx
react/src/FormControl/FormLabel/FormLabel.tsx
react/src/Input/Input.tsx
react/src/Pagination/usePaginationRange.ts
react/src/Sidebar/SidebarItem.tsx
react/src/Sidebar/SidebarList.tsx
react/src/Tile/Tile.stories.tsx
react/src/Tile/Tile.tsx
react/src/Toast/useToast.ts
react/src/icons/BxCheckAnimated.tsx
react/src/theme/components/Button.ts
react/src/theme/components/MultiSelect.ts
react/src/theme/components/SingleSelect.ts

refactor: use explicit import for lodash (to reduce bundling whole lib)
fix: mark sideEffects false for package
npm notice package size:  472.8 kB
npm notice unpacked size: 4.4 MB
To check for tree shake

refactor: use explicit import for lodash (to reduce bundling whole lib)

---

packages/camp/src/MultiSelect/MultiSelectProvider.tsx

This issue was first identified on ActiveSG where programme filters would be added twice when users performed the action on mobile. This issue does not exist outside mobile mode. 
Refer to the following recording of the issue:
https://github.com/user-attachments/assets/c2342717-9f22-4a3e-9a3e-20efe3e227f7
The root cause of the issue is still unclear. 
@dextertanyj identified that `itemHandleClick` function in `downshift` is only called once, eliminating the hypothesis that there was a bug in the package that led to the event being fired twice. 
@dextertanyj further identified that on mobile, two events `onClick` and `onMouseMove` are fired at the same time (thus causing two state transitions). The current hypothesis is that this bug arises due to the way React handles both these …

fix(MultiSelectProvider.tsx): double addition on mobile

---

packages/camp/src/Input/Input.stories.tsx
packages/camp/src/Input/Input.tsx
packages/camp/src/theme/components/Input.ts

Properly fixes the passing of `isSuccess` and `isPrefilled` values into the `Input` component.
The initial fix outlined in #754 results in a significant regression as the `sx` prop overwrites all other styling applied via props.
This fix passes the above two values into the actual Chakra `Input` component as data attributes allowing them to safely exist in the DOM element.

fix: themeable input

---

packages/camp/src/DatePicker/DatePicker.stories.tsx
packages/camp/src/DatePicker/utils/pickCalendarProps.ts
packages/camp/src/DateRangePicker/DateRangePicker.stories.tsx
packages/camp/src/DateRangePicker/DateRangePickerContext.tsx
packages/camp/src/DateRangePicker/utils.ts

`DatePicker` wasn't prop-drilling `onYearChange` and `onMonthChange` to the underlying `Calendar`
- Standardise both `DatePicker` and `DateRangePicker` to drill with the `pick()` selector
- Add them 2 to the Calendar props
- Added stories on the parent `DatePicker` so we can assert this correct behaviour

fix: prop drill onYearChange and onMonthChange

---

packages/camp/src/MultiSelect/MultiSelect.stories.tsx
packages/camp/src/MultiSelect/components/MultiSelectItem/MultiSelectItem.tsx
packages/camp/src/TagInput/TagInput.stories.tsx
packages/camp/src/TagInput/TagInput.tsx
packages/camp/src/TagInput/TagInputTag.tsx
packages/camp/src/theme/components/TagInput.ts

The delete buttons on tags within MultiSelect and TagInput components are not disabled when the field is readonly. This violates the readonly state of the field.
Also TagInput currently does not support overriding of Tag styles.
Check if the field is readonly and disable the button.
Add a new Tag part style for TagInput.
Includes stories for testing.

fix: disable tag delete button on readonly
